services:
  mysql:
    image: mariadb:10.6
    container_name: bilibili_live_mariadb
    restart: always
    tty: true
    environment:
      TZ: Asia/Shanghai
      MARIADB_DATABASE: bilibiliLiveMonitor
      MARIADB_ROOT_PASSWORD: nu4x599Wq7u0Bn8EABh3J91G
    volumes:
      - /data/bilibiliLiveMonitor/mariadb/data:/var/lib/mysql
      - /data/bilibiliLiveMonitor/mariadb/init:/docker-entrypoint-initdb.d
    ports:
      - 3609:3306
    healthcheck:
      test: "mysql -h127.0.0.1 -uroot -p$$MARIADB_ROOT_PASSWORD -e 'SHOW DATABASES;'"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - net

  monitor:
    image: lambdaexpression/bilibili-live-monitor:48687d0
    container_name: bilibili_live_monitor
    restart: always
    tty: true
    environment:
      DB_URL: jdbc:mysql://mysql:3306/bilibiliLiveMonitor?useUnicode=true&characterEncoding=utf8
      DB_UESR: root
      DB_PASSWORD: nu4x599Wq7u0Bn8EABh3J91G
    ports:
      - 23333:23333
    volumes:
      - /data/bilibiliLiveMonitor/monitor/log:/data/logs
      - /data/bilibiliLiveMonitor/monitor/data:/data/BiliBili_Danmuji
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - net

networks:
  net: